In [4]:
import csv

l = []

with open(r"C:\Users\Акмира\OneDrive\Документы\GitHub\ICT_2022\practice7\list_symbols_euronext.csv", 'r') as file:
    csvfile1 = csv.reader(file)
    for i in csvfile1:
        l += i

with open(r"C:\Users\Акмира\OneDrive\Документы\GitHub\ICT_2022\practice7\list_symbols_US.csv", 'r') as file:
    csvfile2 = csv.reader(file)
    for i in csvfile2:
        l += i

print(len(l))

10045

In [5]:
import pandas as pd
import requests

for i in range(10):
    try:
        url = "https://query1.finance.yahoo.com/v7/finance/download/"+l[i]+"?period1=0&period2=1661904000&interval=1d&events=history&includeAdjustedClose=true"
        print(pd.read_csv(url))
    except:
        pass

            Date       Open       High        Low      Close  Adj Close  \
0     2006-02-08  23.299999  23.299999  23.299999  23.299999  20.706814
1     2006-02-09  17.950001  17.950001  17.950001  17.950001  15.952249
2     2006-02-10  16.990000  16.990000  16.990000  16.990000  15.099088
3     2006-02-13  18.059999  18.059999  18.059999  18.059999  16.050003
4     2006-02-14  19.000000  19.000000  19.000000  19.000000  16.885384
...          ...        ...        ...        ...        ...        ...
4231  2022-08-24  27.400000  27.400000  25.900000  25.900000  25.900000
4232  2022-08-25  25.900000  25.900000  25.900000  25.900000  25.900000
4233  2022-08-26  25.900000  25.900000  25.900000  25.900000  25.900000
4234  2022-08-29  25.900000  25.900000  25.900000  25.900000  25.900000
4235  2022-08-30  25.900000  25.900000  25.900000  25.900000  25.900000

        Volume
0          0.0
1     177800.0
2      65600.0
3      38200.0
4      23200.0
...        ...
4231     223.0
4232       0.0
4233       0.0
4234       0.0
4235       0.0

[4236 rows x 7 columns]
           Date        Open        High        Low      Close  Adj Close  \
0    2019-07-12   87.199997   90.000000  83.000000  83.000000  78.940155
1    2019-07-15   83.000000   83.980003  81.000000  81.000000  77.037987
2    2019-07-16   81.000000   81.000000  80.000000  81.000000  77.037987
3    2019-07-17   81.000000   81.000000  80.510002  81.000000  77.037987
4    2019-07-18   80.010002   80.010002  77.010002  80.000000  76.086876
..          ...         ...         ...        ...        ...        ...
784  2022-08-24  100.400002  100.400002  97.900002  99.199997  99.069611
785  2022-08-25   98.599998  100.400002  98.599998  99.000000  98.869881
786  2022-08-26   99.900002   99.900002  95.599998  96.699997  96.572899
787  2022-08-29   95.900002   97.199997  93.099998  97.000000  96.872505
788  2022-08-30   97.000000   97.000000  89.500000  90.400002  90.281181

     Volume
0     40831
1      8810
2     21400
3     12966
4      4789
..      ...
784  194443
785  193994
786  199700
787  175237
788  270593

[789 rows x 7 columns]
            Date  Open   High   Low  Close  Adj Close  Volume
0     2018-06-22  9.00  9.680  8.90  9.500      9.500  677679
1     2018-06-25  9.66  9.800  9.10  9.320      9.320  102472
2     2018-06-26  9.56  9.560  9.14  9.220      9.220   35033
3     2018-06-27  9.20  9.340  9.10  9.280      9.280   53496
4     2018-06-28  9.28  9.280  9.20  9.280      9.280    4160
...          ...   ...    ...   ...    ...        ...     ...
1071  2022-08-24  3.05  3.100  3.00  3.055      3.055   13406
1072  2022-08-25  3.02  3.105  3.02  3.105      3.105    3193
1073  2022-08-26  3.06  3.125  3.06  3.070      3.070    2330
1074  2022-08-29  3.00  3.060  3.00  3.040      3.040    3851
1075  2022-08-30  3.08  3.160  3.03  3.160      3.160    4853

[1076 rows x 7 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     2015-06-26  37.513134  39.013657  33.011559  35.412395  35.412395
1     2015-06-29  36.012608  39.013657  33.011559  33.011559  33.011559
2     2015-06-30  33.311661  33.311661  30.010506  30.610716  30.610716
3     2015-07-01  30.610716  30.610716  28.509981  29.890465  29.890465
4     2015-07-02  29.890465  37.213028  29.890465  36.012608  36.012608
...          ...        ...        ...        ...        ...        ...
1800  2022-08-24   1.604000   1.604000   1.524000   1.528000   1.528000
1801  2022-08-25   1.530000   1.590000   1.500000   1.590000   1.590000
1802  2022-08-26   1.590000   1.700000   1.512000   1.650000   1.650000
1803  2022-08-29   1.650000   1.650000   1.554000   1.604000   1.604000
1804  2022-08-30   1.650000   1.880000   1.650000   1.700000   1.700000

       Volume
0       57075
1       12126
2       32690
3       17520
4       50633
...       ...
1800   423168
1801   811684
1802   992757
1803   470334
1804  3940004

[1805 rows x 7 columns]
            Date      Open      High       Low     Close  Adj Close    Volume
0     2000-06-29  0.694444  0.694444  0.694444  0.694444   0.324566  361307.0
1     2000-06-30  0.752314  0.752314  0.752314  0.752314   0.351613    2764.0
2     2000-07-03  0.694444  0.694444  0.694444  0.694444   0.324566    8959.0
3     2000-07-04  0.694444  0.694444  0.694444  0.694444   0.324566    1728.0
4     2000-07-05  0.752314  0.752314  0.752314  0.752314   0.351613       8.0
...          ...       ...       ...       ...       ...        ...       ...
5695  2022-08-24  3.160000  3.210000  3.160000  3.210000   3.210000    5551.0
5696  2022-08-25  3.210000  3.220000  3.060000  3.190000   3.190000    2486.0
5697  2022-08-26  3.170000  3.180000  3.100000  3.180000   3.180000      77.0
5698  2022-08-29  3.060000  3.200000  3.060000  3.070000   3.070000    1741.0
5699  2022-08-30  3.160000  3.160000  3.080000  3.080000   3.080000      45.0

[5700 rows x 7 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     1998-07-20   6.806702   6.863425   6.750000   6.750000   4.139451
1     1998-07-21   6.806702   6.806702   6.693257   6.806702   4.174222
2     1998-07-22   6.784012   6.806702   6.670567   6.670567   4.090738
3     1998-07-23   6.693257   6.806702   6.602500   6.636535   4.069867
4     1998-07-24   6.613845   6.750000   6.579812   6.693257   4.104653
...          ...        ...        ...        ...        ...        ...
6208  2022-08-24  37.639999  37.740002  36.669998  37.590000  37.590000
6209  2022-08-25  38.000000  38.310001  37.410000  38.020000  38.020000
6210  2022-08-26  38.240002  38.580002  37.279999  37.369999  37.369999
6211  2022-08-29  36.939999  37.930000  36.830002  37.549999  37.549999
6212  2022-08-30  37.740002  38.480000  37.169998  37.240002  37.240002

      Volume
0     113444
1      40100
2      55816
3      91660
4      18948
...      ...
6208  134414
6209  149422
6210  145886
6211  172072
6212  191987

[6213 rows x 7 columns]
            Date   Open   High    Low  Close   Adj Close  Volume
0     2016-01-15  120.0  120.0  120.0  120.0   83.772018   200.0
1     2016-01-18  120.0  120.0  120.0  120.0   83.772018     0.0
2     2016-01-19  120.0  120.0  120.0  120.0   83.772018     0.0
3     2016-01-20  120.0  120.0  120.0  120.0   83.772018     0.0
4     2016-01-21  120.0  120.0  120.0  120.0   83.772018     0.0
...          ...    ...    ...    ...    ...         ...     ...
1659  2022-08-24  144.0  144.0  144.0  144.0  144.000000     1.0
1660  2022-08-25  144.0  144.0  144.0  144.0  144.000000     0.0
1661  2022-08-26  145.0  150.0  145.0  150.0  150.000000  1000.0
1662  2022-08-29  149.0  149.0  149.0  149.0  149.000000    36.0
1663  2022-08-30  142.0  142.0  142.0  142.0  142.000000   103.0

[1664 rows x 7 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     2000-12-01  21.624790  22.099924  21.380974  22.006147  -3.526538
1     2000-12-04  22.187449  23.006428  21.881113  22.512539  -3.607690
2     2000-12-05  23.131462  23.819155  22.506287  22.506287  -3.606688
3     2000-12-06  22.193701  22.349995  21.255938  21.318455  -3.416333
4     2000-12-07  21.568525  22.818874  21.468496  22.500034  -3.605685
...          ...        ...        ...        ...        ...        ...
5586  2022-08-24  51.400002  52.430000  51.189999  52.250000  52.250000
5587  2022-08-25  52.500000  52.529999  51.360001  51.360001  51.360001
5588  2022-08-26  51.310001  51.400002  50.110001  50.279999  50.279999
5589  2022-08-29  49.930000  49.930000  49.090000  49.494999  49.494999
5590  2022-08-30  49.709999  50.320000  49.119999  49.240002  49.240002

          Volume
0     14717140.0
1      4323842.0
2      4768189.0
3      5986926.0
4      2223017.0
...          ...
5586   1333209.0
5587   1383478.0
5588   1750257.0
5589   1335523.0
5590   1719216.0

[5591 rows x 7 columns]
            Date   Open    High    Low   Close  Adj Close  Volume
0     2010-04-26  12.98  12.980  12.20  12.680     12.680   62866
1     2010-04-27  12.74  12.830  12.61  12.700     12.700   22370
2     2010-04-28  12.70  12.700  12.41  12.500     12.500    8211
3     2010-04-29  12.60  12.650  12.46  12.640     12.640    4676
4     2010-04-30  12.63  12.710  12.55  12.650     12.650    4470
...          ...    ...     ...    ...     ...        ...     ...
3158  2022-08-24   7.50   7.500   7.28   7.380      7.380   57688
3159  2022-08-25   8.28   9.400   8.26   8.800      8.800  327851
3160  2022-08-26   8.64   9.070   8.57   8.910      8.910  112173
3161  2022-08-29   8.72   9.045   8.60   8.870      8.870   57706
3162  2022-08-30   8.95   9.095   8.86   9.025      9.025   42130

[3163 rows x 7 columns]

In [6]:
import pandas as pd
import requests

dff = []
for i in range(10):
    try:
        url = "https://query1.finance.yahoo.com/v7/finance/download/"+l[i]+"?period1=0&period2=1661904000&interval=1d&events=history&includeAdjustedClose=true"
        df = pd.read_csv(url)
        df['Name'] = l[i]
        print(df)
    except:
        pass

            Date       Open       High        Low      Close  Adj Close  \
0     2006-02-08  23.299999  23.299999  23.299999  23.299999  20.706814
1     2006-02-09  17.950001  17.950001  17.950001  17.950001  15.952243
2     2006-02-10  16.990000  16.990000  16.990000  16.990000  15.099091
3     2006-02-13  18.059999  18.059999  18.059999  18.059999  16.050003
4     2006-02-14  19.000000  19.000000  19.000000  19.000000  16.885386
...          ...        ...        ...        ...        ...        ...
4231  2022-08-24  27.400000  27.400000  25.900000  25.900000  25.900000
4232  2022-08-25  25.900000  25.900000  25.900000  25.900000  25.900000
4233  2022-08-26  25.900000  25.900000  25.900000  25.900000  25.900000
4234  2022-08-29  25.900000  25.900000  25.900000  25.900000  25.900000
4235  2022-08-30  25.900000  25.900000  25.900000  25.900000  25.900000

        Volume      Name
0          0.0  ALMIL.PA
1     177800.0  ALMIL.PA
2      65600.0  ALMIL.PA
3      38200.0  ALMIL.PA
4      23200.0  ALMIL.PA
...        ...       ...
4231     223.0  ALMIL.PA
4232       0.0  ALMIL.PA
4233       0.0  ALMIL.PA
4234       0.0  ALMIL.PA
4235       0.0  ALMIL.PA

[4236 rows x 8 columns]
           Date        Open        High        Low      Close  Adj Close  \
0    2019-07-12   87.199997   90.000000  83.000000  83.000000  78.940155
1    2019-07-15   83.000000   83.980003  81.000000  81.000000  77.037979
2    2019-07-16   81.000000   81.000000  80.000000  81.000000  77.037979
3    2019-07-17   81.000000   81.000000  80.510002  81.000000  77.037979
4    2019-07-18   80.010002   80.010002  77.010002  80.000000  76.086899
..          ...         ...         ...        ...        ...        ...
784  2022-08-24  100.400002  100.400002  97.900002  99.199997  99.069611
785  2022-08-25   98.599998  100.400002  98.599998  99.000000  98.869881
786  2022-08-26   99.900002   99.900002  95.599998  96.699997  96.572899
787  2022-08-29   95.900002   97.199997  93.099998  97.000000  96.872505
788  2022-08-30   97.000000   97.000000  89.500000  90.400002  90.281181

     Volume     Name
0     40831  2020.OL
1      8810  2020.OL
2     21400  2020.OL
3     12966  2020.OL
4      4789  2020.OL
..      ...      ...
784  194443  2020.OL
785  193994  2020.OL
786  199700  2020.OL
787  175237  2020.OL
788  270593  2020.OL

[789 rows x 8 columns]
            Date  Open   High   Low  Close  Adj Close  Volume      Name
0     2018-06-22  9.00  9.680  8.90  9.500      9.500  677679  2CRSI.PA
1     2018-06-25  9.66  9.800  9.10  9.320      9.320  102472  2CRSI.PA
2     2018-06-26  9.56  9.560  9.14  9.220      9.220   35033  2CRSI.PA
3     2018-06-27  9.20  9.340  9.10  9.280      9.280   53496  2CRSI.PA
4     2018-06-28  9.28  9.280  9.20  9.280      9.280    4160  2CRSI.PA
...          ...   ...    ...   ...    ...        ...     ...       ...
1071  2022-08-24  3.05  3.100  3.00  3.055      3.055   13406  2CRSI.PA
1072  2022-08-25  3.02  3.105  3.02  3.105      3.105    3193  2CRSI.PA
1073  2022-08-26  3.06  3.125  3.06  3.070      3.070    2330  2CRSI.PA
1074  2022-08-29  3.00  3.060  3.00  3.040      3.040    3851  2CRSI.PA
1075  2022-08-30  3.08  3.160  3.03  3.160      3.160    4853  2CRSI.PA

[1076 rows x 8 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     2015-06-26  37.513134  39.013657  33.011559  35.412395  35.412395
1     2015-06-29  36.012608  39.013657  33.011559  33.011559  33.011559
2     2015-06-30  33.311661  33.311661  30.010506  30.610716  30.610716
3     2015-07-01  30.610716  30.610716  28.509981  29.890465  29.890465
4     2015-07-02  29.890465  37.213028  29.890465  36.012608  36.012608
...          ...        ...        ...        ...        ...        ...
1800  2022-08-24   1.604000   1.604000   1.524000   1.528000   1.528000
1801  2022-08-25   1.530000   1.590000   1.500000   1.590000   1.590000
1802  2022-08-26   1.590000   1.700000   1.512000   1.650000   1.650000
1803  2022-08-29   1.650000   1.650000   1.554000   1.604000   1.604000
1804  2022-08-30   1.650000   1.880000   1.650000   1.700000   1.700000

       Volume    Name
0       57075  5PG.OL
1       12126  5PG.OL
2       32690  5PG.OL
3       17520  5PG.OL
4       50633  5PG.OL
...       ...     ...
1800   423168  5PG.OL
1801   811684  5PG.OL
1802   992757  5PG.OL
1803   470334  5PG.OL
1804  3940004  5PG.OL

[1805 rows x 8 columns]
            Date      Open      High       Low     Close  Adj Close    Volume  \
0     2000-06-29  0.694444  0.694444  0.694444  0.694444   0.324566  361307.0
1     2000-06-30  0.752314  0.752314  0.752314  0.752314   0.351613    2764.0
2     2000-07-03  0.694444  0.694444  0.694444  0.694444   0.324566    8959.0
3     2000-07-04  0.694444  0.694444  0.694444  0.694444   0.324566    1728.0
4     2000-07-05  0.752314  0.752314  0.752314  0.752314   0.351613       8.0
...          ...       ...       ...       ...       ...        ...       ...
5695  2022-08-24  3.160000  3.210000  3.160000  3.210000   3.210000    5551.0
5696  2022-08-25  3.210000  3.220000  3.060000  3.190000   3.190000    2486.0
5697  2022-08-26  3.170000  3.180000  3.100000  3.180000   3.180000      77.0
5698  2022-08-29  3.060000  3.200000  3.060000  3.070000   3.070000    1741.0
5699  2022-08-30  3.160000  3.160000  3.080000  3.080000   3.080000      45.0

          Name
0     ALAST.PA
1     ALAST.PA
2     ALAST.PA
3     ALAST.PA
4     ALAST.PA
...        ...
5695  ALAST.PA
5696  ALAST.PA
5697  ALAST.PA
5698  ALAST.PA
5699  ALAST.PA

[5700 rows x 8 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     1998-07-20   6.806702   6.863425   6.750000   6.750000   4.139450
1     1998-07-21   6.806702   6.806702   6.693257   6.806702   4.174223
2     1998-07-22   6.784012   6.806702   6.670567   6.670567   4.090737
3     1998-07-23   6.693257   6.806702   6.602500   6.636535   4.069867
4     1998-07-24   6.613845   6.750000   6.579812   6.693257   4.104652
...          ...        ...        ...        ...        ...        ...
6208  2022-08-24  37.639999  37.740002  36.669998  37.590000  37.590000
6209  2022-08-25  38.000000  38.310001  37.410000  38.020000  38.020000
6210  2022-08-26  38.240002  38.580002  37.279999  37.369999  37.369999
6211  2022-08-29  36.939999  37.930000  36.830002  37.549999  37.549999
6212  2022-08-30  37.740002  38.480000  37.169998  37.240002  37.240002

      Volume     Name
0     113444  AALB.AS
1      40100  AALB.AS
2      55816  AALB.AS
3      91660  AALB.AS
4      18948  AALB.AS
...      ...      ...
6208  134414  AALB.AS
6209  149422  AALB.AS
6210  145886  AALB.AS
6211  172072  AALB.AS
6212  191987  AALB.AS

[6213 rows x 8 columns]
            Date   Open   High    Low  Close   Adj Close  Volume     Name
0     2016-01-15  120.0  120.0  120.0  120.0   83.772018   200.0  AASB.OL
1     2016-01-18  120.0  120.0  120.0  120.0   83.772018     0.0  AASB.OL
2     2016-01-19  120.0  120.0  120.0  120.0   83.772018     0.0  AASB.OL
3     2016-01-20  120.0  120.0  120.0  120.0   83.772018     0.0  AASB.OL
4     2016-01-21  120.0  120.0  120.0  120.0   83.772018     0.0  AASB.OL
...          ...    ...    ...    ...    ...         ...     ...      ...
1659  2022-08-24  144.0  144.0  144.0  144.0  144.000000     1.0  AASB.OL
1660  2022-08-25  144.0  144.0  144.0  144.0  144.000000     0.0  AASB.OL
1661  2022-08-26  145.0  150.0  145.0  150.0  150.000000  1000.0  AASB.OL
1662  2022-08-29  149.0  149.0  149.0  149.0  149.000000    36.0  AASB.OL
1663  2022-08-30  142.0  142.0  142.0  142.0  142.000000   103.0  AASB.OL

[1664 rows x 8 columns]
            Date       Open       High        Low      Close  Adj Close  \
0     2000-12-01  21.624790  22.099924  21.380974  22.006147  -3.526539
1     2000-12-04  22.187449  23.006428  21.881113  22.512539  -3.607689
2     2000-12-05  23.131462  23.819155  22.506287  22.506287  -3.606687
3     2000-12-06  22.193701  22.349995  21.255938  21.318455  -3.416334
4     2000-12-07  21.568525  22.818874  21.468496  22.500034  -3.605686
...          ...        ...        ...        ...        ...        ...
5586  2022-08-24  51.400002  52.430000  51.189999  52.250000  52.250000
5587  2022-08-25  52.500000  52.529999  51.360001  51.360001  51.360001
5588  2022-08-26  51.310001  51.400002  50.110001  50.279999  50.279999
5589  2022-08-29  49.930000  49.930000  49.090000  49.494999  49.494999
5590  2022-08-30  49.709999  50.320000  49.119999  49.240002  49.240002

          Volume    Name
0     14717140.0  ABI.BR
1      4323842.0  ABI.BR
2      4768189.0  ABI.BR
3      5986926.0  ABI.BR
4      2223017.0  ABI.BR
...          ...     ...
5586   1333209.0  ABI.BR
5587   1383478.0  ABI.BR
5588   1750257.0  ABI.BR
5589   1335523.0  ABI.BR
5590   1719216.0  ABI.BR

[5591 rows x 8 columns]
            Date   Open    High    Low   Close  Adj Close  Volume   Name
0     2010-04-26  12.98  12.980  12.20  12.680     12.680   62866  AB.PA
1     2010-04-27  12.74  12.830  12.61  12.700     12.700   22370  AB.PA
2     2010-04-28  12.70  12.700  12.41  12.500     12.500    8211  AB.PA
3     2010-04-29  12.60  12.650  12.46  12.640     12.640    4676  AB.PA
4     2010-04-30  12.63  12.710  12.55  12.650     12.650    4470  AB.PA
...          ...    ...     ...    ...     ...        ...     ...    ...
3158  2022-08-24   7.50   7.500   7.28   7.380      7.380   57688  AB.PA
3159  2022-08-25   8.28   9.400   8.26   8.800      8.800  327851  AB.PA
3160  2022-08-26   8.64   9.070   8.57   8.910      8.910  112173  AB.PA
3161  2022-08-29   8.72   9.045   8.60   8.870      8.870   57706  AB.PA
3162  2022-08-30   8.95   9.095   8.86   9.025      9.025   42130  AB.PA

[3163 rows x 8 columns]

In [10]:
import pandas as pd
import requests

dff = []
for i in range(10):
    try:
        url = "https://query1.finance.yahoo.com/v7/finance/download/"+l[i]+"?period1=0&period2=1661904000&interval=1d&events=history&includeAdjustedClose=true"
        df = pd.read_csv(url)
        df['Name'] = l[i]
        dff.append(df)
        # print(df)
    except:
        pass

print(pd.concat(dff, ignore_index=True))

# df.to_csv(r"C:\Users\Акмира\OneDrive\Документы\GitHub\ICT_2022\lecture7\mycsv.csv")
# df.to_parquet(r"C:\Users\Акмира\OneDrive\Документы\GitHub\ICT_2022\practice7\mycsv_par.parquet")

             Date       Open       High        Low      Close  Adj Close  \
0      2006-02-08  23.299999  23.299999  23.299999  23.299999  20.706816
1      2006-02-09  17.950001  17.950001  17.950001  17.950001  15.952247
2      2006-02-10  16.990000  16.990000  16.990000  16.990000  15.099088
3      2006-02-13  18.059999  18.059999  18.059999  18.059999  16.050003
4      2006-02-14  19.000000  19.000000  19.000000  19.000000  16.885387
...           ...        ...        ...        ...        ...        ...
30232  2022-08-24   7.500000   7.500000   7.280000   7.380000   7.380000
30233  2022-08-25   8.280000   9.400000   8.260000   8.800000   8.800000
30234  2022-08-26   8.640000   9.070000   8.570000   8.910000   8.910000
30235  2022-08-29   8.720000   9.045000   8.600000   8.870000   8.870000
30236  2022-08-30   8.950000   9.095000   8.860000   9.025000   9.025000

         Volume      Name
0           0.0  ALMIL.PA
1      177800.0  ALMIL.PA
2       65600.0  ALMIL.PA
3       38200.0  ALMIL.PA
4       23200.0  ALMIL.PA
...         ...       ...
30232   57688.0     AB.PA
30233  327851.0     AB.PA
30234  112173.0     AB.PA
30235   57706.0     AB.PA
30236   42130.0     AB.PA

[30237 rows x 8 columns]